language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules
    
install:
  - npm install

script:
  - ng build --prod --base-href http://abhinavagrawal.in/cs5200-final-project/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bookit
  on:
    branch: master