language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules
    
install:
  - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 3cdeb9c033a5ddc4176c2163566d3cbbcd9c158a
  local_dir: dist/bookit
  on:
    branch: master