language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules
    
install:
  - npm install

script:
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 406b82e68b252f17341b744f1bd7e7d44e826396
  local_dir: dist/bookit
  on:
    branch: master